package io.licensemanager.backend.configuration.setup;

public enum AVAILABLE_ROLES_PERMISSIONS {
    ALL,
    VIEW_ALL_LICENSES,
    VIEW_SELF_LICENSES,
    EDIT_ALL_LICENSES,
    EDIT_SELF_LICENSES,
    NOTIFICATIONS_ALL,
    NOTIFICATIONS_ALL_LICENSES,
    NOTIFICATIONS_SELF_LICENSES
}
