package io.licensemanager.backend.configuration.setup;

public enum ROLES_PERMISSIONS {
    ALL,
    VIEW_ALL_LICENSES,
    EDIT_ALL_LICENSES,
    DELETE_ALL_LICENSES,
    VIEW_ALL_CUSTOMERS,
    EDIT_ALL_CUSTOMERS,
    DELETE_ALL_CUSTOMERS,
    NOTIFICATIONS_ALL,
    NOTIFICATIONS_ALL_LICENSES,
}
